# Generated by Django 3.0.3 on 2020-02-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loganalize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logfile',
            old_name='path',
            new_name='name',
        ),
    ]
